export const IDENTITY_ERROR_CODES = {
  ROLE_CODE_TAKEN: 'IDENTITY_ROLE_CODE_TAKEN',
  ROLE_NOT_FOUND: 'IDENTITY_ROLE_NOT_FOUND',
  ROLE_IS_SYSTEM: 'IDENTITY_ROLE_IS_SYSTEM',
  ROLE_VALIDATION_FAILED: 'IDENTITY_ROLE_VALIDATION_FAILED',
  UNKNOWN_PERMISSION_CODE: 'IDENTITY_UNKNOWN_PERMISSION_CODE',
  USER_NOT_FOUND: 'IDENTITY_USER_NOT_FOUND',
  ROLE_ALREADY_ASSIGNED: 'IDENTITY_ROLE_ALREADY_ASSIGNED',
  USER_CODE_TAKEN: 'IDENTITY_USER_CODE_TAKEN',
} as const;

/** The Postgres constraint names from `1809000000000-CreateRbac.ts` and `1810000000000-UsersProfileFields.ts`. */
export const IDENTITY_CONSTRAINTS = {
  ROLE_CODE_UNIQUE: 'UQ_roles_code',
  USER_CODE_UNIQUE: 'UQ_users_code',
} as const;
