export const WORKFLOW_ERROR_CODES = {
  WORKFLOW_CODE_TAKEN: 'WORKFLOW_CODE_TAKEN',
  WORKFLOW_NOT_FOUND: 'WORKFLOW_NOT_FOUND',
  WORKFLOW_VALIDATION_FAILED: 'WORKFLOW_VALIDATION_FAILED',
  WORKFLOW_IN_USE: 'WORKFLOW_IN_USE',
  CONFIG_INVALID: 'WORKFLOW_CONFIG_INVALID',
  NO_DRAFT_VERSION: 'WORKFLOW_NO_DRAFT_VERSION',
  DRAFT_ALREADY_EXISTS: 'WORKFLOW_DRAFT_ALREADY_EXISTS',
  VERSION_NOT_FOUND: 'WORKFLOW_VERSION_NOT_FOUND',
  VERSION_ALREADY_PUBLISHED: 'WORKFLOW_VERSION_ALREADY_PUBLISHED',
  AI_STEP_CODE_TAKEN: 'AI_PIPELINE_STEP_CODE_TAKEN',
  AI_STEP_NOT_FOUND: 'AI_PIPELINE_STEP_NOT_FOUND',
} as const;

/** The Postgres constraint names from `1812000000000-CreateWorkflows.ts` and `1813000000000-CreateAiPipelineSteps.ts`. */
export const WORKFLOW_CONSTRAINTS = {
  WORKFLOW_CODE_UNIQUE: 'UQ_workflows_code',
  AI_STEP_CODE_UNIQUE: 'UQ_ai_pipeline_steps_code',
} as const;
