import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Initial schema for the web capture flow: a session, the photos taken
 * within it, and the outbox that drains them to the file-service.
 *
 * Not a port of the kiosk's SQLite schema - that one is built for a single
 * writer on one machine and leans on AUTOINCREMENT for ordering. This is a
 * server several browsers talk to at once, so identifiers are generated by
 * the database (uuid) and timestamps carry a zone (timestamptz).
 */
export class InitCaptureSchema1787300000000 implements MigrationInterface {
  name = 'InitCaptureSchema1787300000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TYPE "sessions_status_enum" AS ENUM ('IN_PROGRESS', 'COMPLETED', 'CANCELLED')`,
    );
    await queryRunner.query(`
      CREATE TABLE "sessions" (
        "id" uuid NOT NULL DEFAULT gen_random_uuid(),
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "subject_code" character varying(100),
        "subject_name" character varying(255),
        "status" "sessions_status_enum" NOT NULL DEFAULT 'IN_PROGRESS',
        "completed_at" TIMESTAMP WITH TIME ZONE,
        "metadata" jsonb NOT NULL DEFAULT '{}',
        CONSTRAINT "PK_sessions" PRIMARY KEY ("id")
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IDX_sessions_created_at" ON "sessions" ("created_at")`,
    );

    await queryRunner.query(`
      CREATE TABLE "photos" (
        "id" uuid NOT NULL DEFAULT gen_random_uuid(),
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "session_id" uuid NOT NULL,
        "step_id" character varying(50) NOT NULL,
        "attempt" integer NOT NULL DEFAULT 1,
        "mime_type" character varying(100) NOT NULL,
        "bytes" integer NOT NULL,
        "sha256" character varying(64) NOT NULL,
        "fs_file_id" uuid,
        "fs_etag" character varying(255),
        "fs_status" character varying(50),
        "virtual_path" text,
        CONSTRAINT "PK_photos" PRIMARY KEY ("id"),
        CONSTRAINT "CHK_photos_bytes_positive" CHECK ("bytes" > 0),
        CONSTRAINT "FK_photos_session" FOREIGN KEY ("session_id")
          REFERENCES "sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IDX_photos_created_at" ON "photos" ("created_at")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_photos_session_id" ON "photos" ("session_id")`,
    );
    // A retake is a new attempt, never an overwrite of an earlier one - the
    // earlier photo must survive until the operator has chosen between them.
    // This is what makes that a database constraint, not just an application
    // convention a bug could quietly violate.
    await queryRunner.query(
      `CREATE UNIQUE INDEX "IDX_photos_session_step_attempt" ON "photos" ("session_id", "step_id", "attempt")`,
    );

    await queryRunner.query(
      `CREATE TYPE "upload_outbox_status_enum" AS ENUM ('PENDING', 'SENDING', 'UPLOADED', 'FAILED')`,
    );
    await queryRunner.query(`
      CREATE TABLE "upload_outbox" (
        "id" uuid NOT NULL DEFAULT gen_random_uuid(),
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "photo_id" uuid NOT NULL,
        "idem_key" character varying(255) NOT NULL,
        "virtual_path" text NOT NULL,
        "mime_type" character varying(100) NOT NULL,
        "content" bytea NOT NULL,
        "status" "upload_outbox_status_enum" NOT NULL DEFAULT 'PENDING',
        "attempts" integer NOT NULL DEFAULT 0,
        "last_error" text,
        "next_retry_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_upload_outbox" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_upload_outbox_idem_key" UNIQUE ("idem_key"),
        CONSTRAINT "FK_upload_outbox_photo" FOREIGN KEY ("photo_id")
          REFERENCES "photos"("id") ON DELETE CASCADE ON UPDATE NO ACTION
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IDX_upload_outbox_created_at" ON "upload_outbox" ("created_at")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_upload_outbox_status" ON "upload_outbox" ("status")`,
    );
    // Partial index on the exact predicate `claimNext` filters by - keeps the
    // due-work scan cheap once FAILED/UPLOADED rows pile up.
    await queryRunner.query(`
      CREATE INDEX "IDX_upload_outbox_due" ON "upload_outbox" ("status", "next_retry_at")
        WHERE "status" IN ('PENDING', 'SENDING')
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "upload_outbox"`);
    await queryRunner.query(`DROP TYPE "upload_outbox_status_enum"`);
    await queryRunner.query(`DROP TABLE "photos"`);
    await queryRunner.query(`DROP TABLE "sessions"`);
    await queryRunner.query(`DROP TYPE "sessions_status_enum"`);
  }
}
