/**
 * Domain error codes used by CustomException. Grouped by module, each with its
 * own numeric range so codes stay unique and it's obvious where an error came
 * from just by looking at the number. Extend a range as new modules are added.
 */
export const ERROR_CODE = {
  VALIDATION_ERROR: 1,
  PARAM_ERROR: 1, // Alias for VALIDATION_ERROR
  RECORD_NOT_FOUND: 404, // Alias for NOT_FOUND

  // HTTP
  NOT_FOUND: 404,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  BAD_REQUEST: 400,
  CONFLICT: 409,
  TOO_MANY_REQUESTS: 429,
  UNPROCESSABLE_ENTITY: 422,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  NOT_IMPLEMENTED: 501,

  // CAPTURE SESSION (1xxx)
  SESSION_NOT_FOUND: 1000,
  SESSION_ALREADY_COMPLETED: 1001,
  SESSION_REPORT_INVALID_PAYLOAD: 1002,

  // PHOTO (2xxx)
  PHOTO_NOT_FOUND: 2000,
  PHOTO_INVALID_DATA_URL: 2001,
  PHOTO_UNSUPPORTED_MIME_TYPE: 2002,
  PHOTO_TOO_LARGE: 2003,
  PHOTO_STATUS_INVALID_PAYLOAD: 2004,

  // FILE STORAGE / file-service integration (3xxx)
  FILE_STORAGE_NOT_READY: 3000,
  FILE_STORAGE_UPSTREAM_ERROR: 3001,

  // AUTH (4xxx)
  API_KEY_MISSING: 4000,
  API_KEY_INVALID: 4001,

  // DEVICE MANAGEMENT — campaigns/devices/CMS (5xxx)
  CAMPAIGN_NOT_FOUND: 5000,
  DEVICE_NOT_FOUND: 5001,
  DEVICE_NOT_REGISTERED: 5002,
  DEVICE_EXPIRED: 5003,
  DEVICE_ALREADY_ACTIVATED: 5004,
  DEVICE_SECRET_INVALID: 5005,
  INSTALLER_NOT_CONFIGURED: 5006,
  CAMPAIGN_HAS_DEPENDENCIES: 5007,
};

export const ERROR_TYPE = {};
